Tolerate default commit signing with SSH in tests (#1124)
* Be tolerant of SSH commit signing in tests

If the current git setup has SSH based code signing enabled
(gpg.format=ssh)[1] then the tests fail (even though not signing) as
jgit fails to parse the config with an error like:

```
java.lang.IllegalArgumentException: Invalid value: gpg.format=ssh
        at org.eclipse.jgit.lib.DefaultTypedConfigGetter.getEnum(DefaultTypedConfigGetter.java:103)
        at org.eclipse.jgit.lib.Config.getEnum(Config.java:454)
        at org.eclipse.jgit.lib.GpgConfig.<init>(GpgConfig.java:86)
        at org.eclipse.jgit.api.CommitCommand.processOptions(CommitCommand.java:662)
        at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:189)
        at org.jenkinsci.plugins.gitclient.JGitAPIImpl.commit(JGitAPIImpl.java:487)
        at org.jenkinsci.plugins.gitclient.GitClientMaintenanceTest.commitFile(GitClientMaintenanceTest.java:230)
        at org.jenkinsci.plugins.gitclient.GitClientMaintenanceTest.commitOneFile(GitClientMaintenanceTest.java:224)
        at org.jenkinsci.plugins.gitclient.GitClientMaintenanceTest.commitSeveralFiles(GitClientMaintenanceTest.java:218)
        at org.jenkinsci.plugins.gitclient.GitClientMaintenanceTest.test_gc_maintenance(GitClientMaintenanceTest.java:333)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

[1] https://git-scm.com/docs/git-config#Documentation/git-config.txt-gpgformat

* Remove unused code segment

Only write local git config if in local repo

Update source formatting

Wrap the comment

* Use --local when setting local test options

* Use --local in more tests for better consistency

The `--local` argument will cause command line git to fail if the command
is not performed inside a valid repository. That is a good thing because
the tests should avoid changing global configuration where ever possible.

* Remove some duplicated code from tests

Move workspace initialization into WorkspaceWithRepo

* Deduplicate test repo configuration

* Remove more duplicates

* Remove more duplication

* Remove one more duplication

* Use GitClient.config instead of direct command line

---------

Co-authored-by: Mark Waite <mark.earl.waite@gmail.com>
Co-authored-by: git-client-user <git-client-user@example.com>