[JENKINS-21248] Improve shallow submodule update implementation
* in case the used git does not support shallow submodules, just
  log a warning instead of throwing an exception
* Javadoc texts are used from the already existing CloneCommand
* tests are running fine now and cover more cases
  * file:// has to be used as protocol for local remotes,
    otherwise git doesn't perform shallow cloning
  * a local repository has to be used for shallow clone testing,
    because GitHub doesn't allow fetching dedicated commits
    * see https://github.com/isaacs/github/issues/436
    * this would result in the following
      error: Server does not allow request for unadvertised object
* other minor improvements