Revert "Update JGit to 3.5.0" - breaks tests on Windows
This reverts commit a237f294af4bb89ebe685e4d103dd6dfe4182745.

JGit 3.5.0 fails to create bare repositories on Windows.  JGit 3.4.1
was able to create bare repositories on Windows.

It reports a stack trace like the following:

java.lang.IllegalArgumentException: Hiding only allowed for names that start with a period
	at org.eclipse.jgit.util.FS.setHidden(FS.java:599)
	at org.eclipse.jgit.internal.storage.file.FileRepository.create(FileRepository.java:277)
	at org.eclipse.jgit.api.InitCommand.call(InitCommand.java:92)
	at org.jenkinsci.plugins.gitclient.JGitAPIImpl.doInit(JGitAPIImpl.java:158)
	at org.jenkinsci.plugins.gitclient.JGitAPIImpl.access$600(JGitAPIImpl.java:97)
	at org.jenkinsci.plugins.gitclient.JGitAPIImpl$7.execute(JGitAPIImpl.java:1161)
	at org.jenkinsci.plugins.gitclient.GitAPITestCase$WorkingArea.init(GitAPITestCase.java:175)
	at org.jenkinsci.plugins.gitclient.GitAPITestCase.test_bare_repo_init(GitAPITestCase.java:2750)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jenkinsci.plugins.gitclient.JGitAPIImplTest.runTest(JGitAPIImplTest.java:36)